name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true

    - name: Build Docker image
      run: docker build -t solanamirror/api:latest .

    - name: Save Docker image to file
      run: docker save -o solanamirror-api-latest.tar solanamirror/api:latest

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: solanamirror-api
        path: solanamirror-api.tar

    # Enable tests once they are written
    # - name: Run tests
    #   run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master' 

    steps: 
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: solanamirror-api

    - name: Load Docker image from file
      run: docker load -i solanamirror-api.tar

    - name: List Docker images
      run: docker images

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push solanamirror/api:latest

