name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    
      run: cargo build --release
      run: docker build -t solanamirror/api:latest .

    # Enable tests once they are written
    # run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' 

    steps: 
    - uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker push solanamirror/api:latest

