name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "gh-actions" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --verbose

    # Enable tests once they are written
    # - name: Run tests
    #   run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/head/master' 

    steps: 
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.GCP_VPS_HOST }}
          username: ${{ secrets.GCP_VPS_USER }}
          key: ${{ secrets.GCP_VPS_PRIVATE_KEY }}
          script: |
            touch hello.txt
            echo "Hello from Github Actions" << hello.txt
